[tool.autopep8]
indent_size = 2
max_line_length = 100
ignore = "E121,E125,E126,E129,E226,E302,E305,E501,W504,E741,E704"
exclude = ".ipynb_checkpoints"
aggressive = 3
recursive = true

[tool.mypy]
ignore_missing_imports = true
strict = false
check_untyped_defs = true

[tool.pylint.main]
# See pylint options using "pylint --generate-toml-config"
disable = [
  "unspecified-encoding", "fixme", "redefined-builtin", "cell-var-from-loop",
  "using-constant-test", "simplifiable-condition", "import-outside-toplevel", "line-too-long",
  "too-many-lines", "too-few-public-methods", "too-many-arguments", "too-many-locals",
  # For advent:
  "missing-module-docstring", "missing-function-docstring", "redefined-outer-name", "missing-class-docstring",
  "too-many-branches", "too-many-statements", "multiple-statements", "condition-evals-to-constant",
  # Buggy pylint:
  "inconsistent-return-statements", "redundant-keyword-arg", "unbalanced-tuple-unpacking"
]
reports = false
score = false
recursive = true
ignore-paths = [".ipynb_checkpoints"]

[tool.pylint.basic]
good-names-rgxs = "^[a-z][a-z0-9]?|[A-Z]([A-Z_]*[A-Z])?$"

[tool.pylint.format]
indent-string = "  "
expected-line-ending-format = "LF"
